favicon: '/img/favicon.ico'

navbar:
  logo: '/img/logo.png'
  logo_text: 'IoT'
  links:
    zh-CN:
      - logo: 'fas fa-book'
        text: '文档'
        url: '/'
      - logo: 'fab fa-github'
        text: 'Github'
        url: 'https://github.com/negoces/docs'
      - logo: 'fab fa-github'
        text: 'Github(镜像)'
        url: 'https://hub.fastgit.org/negoces/docs'

sidebar:
  zh-CN:
    docs:
      level: 2
      items:
        - 其他:
          - 编写文档 | docs/others/writting
          - 额外语法 | docs/others/shortcut

github:
  repo: negoces/docs
  edit_on_github: true
