favicon: '/img/favicon.ico'

navbar:
  logo: '/img/logo.png'
  logo_text: 'IoT'
  links:
    zh-CN:
      - logo: 'fas fa-book'
        text: '文档'
        url: '/'
      - logo: 'fab fa-github'
        text: 'Github'
        url: 'https://github.com/negoces/docs'
      - logo: 'fab fa-github'
        text: 'Github(镜像)'
        url: 'https://hub.fastgit.org/negoces/docs'

sidebar:
  zh-CN:
    docs:
      level: 2
      items:
        - 必读:
          - 仓库权限 | docs/readme/repo_perms/
          - 如何贡献(核心成员) | docs/readme/commit_guide_admin/
          - 如何贡献(普通成员) | docs/readme/commit_guide_member/
          - 目录结构 | docs/readme/dir_struct/
          - 编写文档 | docs/readme/writting/
          - 本地预览 | docs/readme/preview/
          - 提交规范 | docs/readme/commit_spec/
        - STM32:
          - 0.介绍&入门 | docs/stm32/intro/
          - 1.开发环境搭建 | docs/stm32/setup_devenv/
          - 2.GPIO使用 | docs/stm32/GPIO/
        - 其他:
          - 额外语法 | docs/others/shortcut/


github:
  repo: negoces/docs
  edit_on_github: true
